### PR TITLE
fix(core): only list admin repos

### LINKED ISSUE #1: List only repositories you can actually delete
## Bug description

You cannot delete repositories without being ADMIN. We should therefore avoid listing them.

### PR DESCRIPTION
**Pull request by Haroenv**
fixes #1

CI requires #2 to be run before this can pass

### CODE REVIEW

**Comment by Haroenv** [comment]
makes sense, a bit of text at the end on the non admin ones that says "can't be deleted by you" could be good IMO

**Comment by Haroenv** [comment]
I made it into an option (`--only-admin`); and by default added a text which says `you are admin` or `you are not admin` (in green or red)

File: src/cli/githubRepositoriesArchiver.js [hunk 1]
```diff
@@ -101,7 +106,7 @@ function githubRepositoriesArchiver(archivePath, options) {
           results[e.full_name] = {
             name: `${e.full_name}${lock} (${chalk.bold(e.stargazers_count)} ⭐️, last updated ${chalk.bold(
               moment(e.updated_at).fromNow()
-            )}${emojis})`,
+            )}${emojis}) ${adminStatus}`,
```
Comment (redox) [inline src/cli/githubRepositoriesArchiver.js]: What about we make it less verbose here?

```js
` )}${emojis}${e.permissions.admin ? '' : chalk.red(' non-deletable')})`
```
